name: json_api_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/breadkey/dart-json-api-generator

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  build: ^2.4.1
  source_gen: ^1.5.0
  json_api_annotation:
    git: https://github.com/breadkey/dart-json-api-generator
      ref: main
      path: json_api_annotation

dev_dependencies:
  build_runner: ^2.4.8
  lints: ^3.0.0
  test: ^1.24.0
